name: mon_store_flutter
description: Un store Android personnalisé pour tes applis
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.14.0
  url_launcher: ^6.0.20

flutter:
  uses-material-design: true
